apiVersion: v1
kind: Service
metadata:
  name: hello-nginxx

spec:
  type: NodePort
  selector:
    app: hello-nginxx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32057
